aws-samples/aws-secure-environment-accelerator

.github/workflows/documentation.yml

The GitHub Action `actions/upload-artifact` has a limitation (described [here](https://github.com/actions/upload-artifact#zipped-artifact-downloads) related to directory artifacts. Directories are dynamically zipped on download; thus there's no need to zip in the action itself.

Fixing double zip issue with documentation build

---

reference-artifacts/config.example.json
reference-artifacts/ssm-documents/s3-encryption.yaml
src/deployments/cdk/src/apps/phase-3.ts
src/deployments/cdk/src/deployments/config/create.ts

- Using "AutomationAssumeRole" if customer provided in ssm document parametrs instead of PipelineRole.
- Passing Static values as SSM Document parametrs.
- Adding SEA:S3BucketEncryptionKey as parameter value, which will replace by KMS Key created for Account Bucket encryption.
- Adding SSM Document for Encrypting S3 Bucket if not encrypted.
- Adding AWS Config rule "S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED" configuration to config example.

feat(core): Config Rules Remediation

---

src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts

- Using "public.ecr.aws/bitnami/node:latest" 

fix(core): Using public ECR image for preDeploy to avoid Docker Throttling

---

src/deployments/cdk/src/apps/phase-2.ts
src/lib/common-outputs/src/stack-output.ts
src/lib/common-outputs/src/vpc.ts

- Maintaining same construct name when a account is suspended by saving in DDB outputsBy submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fix(core): Suspended accounts failure with respect to construct name  change of nested stacks in phase-2

---

src/core/cdk/src/initial-setup.ts
src/core/runtime/src/get-baseline-step.ts
src/core/runtime/src/get-or-create-config.ts

- Adding "storeAllOutputs" property in SM Input which will load all outputs from cfn stacks to DDB tables irrespective of existing entries.

feat(core): Adding "storeAllOutputs" property in SM input

---

src/core/runtime/src/save-outputs-to-ssm/elb-outputs.ts
src/lib/common-config/src/index.ts

- Fix storing rsyslog outputs in SSM of remote accounts based on "populate-all-elbs-in-param-store".
- Previously failed to save outputs if remote account doesn't have VPCs

fix(core): Storing rsysLog outputs in SSM for Remote Accounts

---

src/core/runtime/src/create-adconnector/create.ts
src/deployments/cdk/src/deployments/mad/step-2.ts
src/lib/common-config/src/index.ts

- Added new param "azs": string[] in deployments/mad and deployments/adc config
- If no azs specified consider first two azs in subnet config

fix(core): MAD Failed to Deploy with 3 AZs in subnet

---

src/deployments/cdk/src/deployments/central-services/step-1.ts
src/deployments/cdk/src/deployments/central-services/step-2.ts
src/deployments/cdk/src/deployments/iam/create-role.ts
src/lib/custom-resources/cdk-iam-create-role/runtime/src/index.ts

- Changing CloudWatch central logging configuration "accountConfig/cwl:false/true".
- Fixing for no CWL central accounts in Ops, Security and log account.

fix(core): Fixing CloudWatch Central logging configuration changes

---

src/core/cdk/src/assets/execution-role.template.json
src/core/cdk/src/initial-setup.ts
src/core/cdk/src/tasks/create-stack-task.ts
src/core/runtime/src/create-stack/create.ts
src/core/runtime/src/create-stack/verify.ts
src/core/runtime/src/get-baseline-step.ts
src/core/runtime/src/load-configuration-step.ts

- Creating CloudFormation stack for creating PipelineRole in Org Accounts by assuming role mentioned in  "global-options/organization-admin-role".

fix(core): Removing StackSet for installing Pipeline role in Org Accounts

---

src/core/runtime/src/enable-trusted-access-for-services-step.ts
src/installer/cdk/assets/save-application-version.js
src/installer/cdk/src/index.ts

- Creating "/accelerator/installed-version" SSM ParamStore and inserting version:1 installed version into it.

fix(core): SSM ParamStore history truncated for installedVersion

---

reference-artifacts/SCPs/FullAWSAccess.json
src/deployments/cdk/src/deployments/artifacts/step-1.ts
src/deployments/cdk/src/deployments/defaults/step-1.ts
src/lib/custom-resources/cdk-s3-copy-files/runtime/src/index.ts

Changing current file copy order as following.
- Performing s3 deployment using aws sync to get latest from repo
- After bucket deployment s3copyfiles to get latest file from customer s3 bucket.
By changing order we will be able to copy files provided in customer bucket which are not in repo to phase0 central bucket

fix(core): File copy mechanism broken

---

src/deployments/cdk/src/deployments/central-endpoints/step-3.ts

- Handling both inbound and outbound to be false in both resolvers

fix(core): Handling both inbound and outbound to be false in both resolvers

---

src/deployments/cdk/src/deployments/security-hub/step-1.ts
src/deployments/cdk/src/deployments/security-hub/step-2.ts
src/deployments/cdk/src/deployments/security-hub/step-3.ts
src/lib/common-config/src/index.ts
src/lib/custom-resources/cdk-cfn-utils/cdk/index.ts
src/lib/custom-resources/cdk-guardduty-admin-setup/runtime/src/index.ts
src/lib/custom-resources/cdk-ssm-document-share/runtime/src/index.ts

- Fixing number of accountIds passing to ssm modify-document-permission
- Fixing number of accounts passing to GuardDuty createMembers, updateMembers and deleteMembers
- Adding security-hub-excl-regions and not enabling security hub in those regions

fix(core): Fixing SSM-Document-Share

---

src/lib/custom-resources/cdk-logs-metric-filter/runtime/src/index.ts

It is possible to define non-existent log groups in the metrics definitions in the accelerator config file. These metrics are used in alarms which are configured to be "OK" if there is missing data (i.e. no metric information). This then means that the alarms will never trigger missing the security event. To resolve this the accelerator should not WARN on a missing log group when creating the metric but instead ERROR and fail the deployment.

added error catching for failed log metrics

---

reference-artifacts/SAMPLE_CONFIGS/sample_snippets.md
src/core/runtime/src/add-scp-step.ts
src/lib/common-config/src/index.ts
src/lib/common/src/scp/index.ts

Reverts aws-samples/aws-secure-environment-accelerator#691
- not working as expected, SM execution removes account level scp's even when no SCP line item defined.
- please resubmit once fixed.

Revert "feat(core) Enable account level SCP mgmt"

---

src/deployments/cdk/src/common/interface-endpoints.ts
src/deployments/cdk/src/deployments/vpc/step-3.ts
src/installer/cdk/src/index.ts
src/lib/common-config/src/index.ts

1. Tighten permissions on: PBMMAccel-CB-Installer role
2. Tighten VPC interface endpoint security group permissions
Added new sections 
"global-options/endpoint-port-orverides": {
"application-autoscaling": ["TCP:443", "TCP:8443", "TCP:943"],
"codecommit": ["TCP:443", "UDP:9418"],
"logs": ["TCP:443", "UDP:9418"]
}
"vpc/interface-endpoints/allowed-cidrs": ["10.0.0.0/8", "100.96.252.0/23"],

fix(core): Minor Security Enhancements

---

reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json

SSM session timeout in config lite deployment.  The config lite was missing the 'logs' and 'monitoring' interface endpoints.

SSM session timeout in config lite deployment.  The config lite was missing the 'logs' and 'monitoring' interface endpoints.

---

reference-artifacts/Custom-Scripts/SEA-uninstall/aws-sea-cleanup.py

1. It is not mandatory to supply a deployments key so we should check if this doesn't exist.
2. The cleanup script does not currently delete resolver or endpoint stacks if provisioned, this causes the cleanup script to fail to delete stacks further on due to dependencies. This code deletes the dependent stacks to enable cleanup.

updated script to included deletion of endpoint and phz stacks

---

reference-artifacts/Custom-Scripts/SEA-uninstall/aws-sea-cleanup.py

This stack also needs removing or old outputs are made available to new deployments in the same set of accounts causing failure on subsequent runs.

missed cleaning up zone file outputs in mgmt accounts

---

docs/faq/faq.md
docs/installation/installation.md
docs/installation/sm_inputs.md
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
reference-artifacts/SAMPLE_CONFIGS/sample_snippets.md
reference-artifacts/SCPs/ASEA-Guardrails-Part1.json

- update vpc CIDR2 to array in sample configs
- remove CIDR2 from subnets in sample configs
- update sample snippets to include account level SCPs
- update sample snippets to include interface endpoint security group enhancements
- fix assumerole block for SEA created roles

(docs) Documentation and sample config file updates for v133 release

---

src/deployments/cdk/src/apps/phase-1.ts
src/deployments/cdk/src/apps/phase-2.ts
src/deployments/cdk/src/common/peering-connection.ts
src/deployments/cdk/src/common/vpc.ts
src/deployments/cdk/src/deployments/firewall/cluster/step-2.ts

- Creating only one role per account in default region with all targets in assume policy
- To make it work for existing installs didn't change name formation, it will still have source and target in role name but role belongs to a source with all targets defined in configuration.
#740 

fix(core): Peering connection role construct issue

---

docs/faq/faq.md
src/deployments/cdk/src/deployments/firewall/cluster/step-3.ts
src/lib/cdk-constructs/src/firewall/instance.ts
src/lib/common-config/src/index.ts

Ability to specify `private-ips` within the `ports` section of the firewall configuration.  
Where a private IP is assigned for a subnet and availability zone it will be used in the resulting Network Interface section of the CloudFormation template.  
Where `pritate-ips` is not present allocation will occur as it has historically by automatic assignment during instance launch.
See updates in the FAQ for implementation syntax in the `config.json` file.

Feature: Static IP Assignments for Private ENIs for Fortinet Firewall Subnet Attachments

---

reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json

The CloudFront Console fails to apply an Origin Access Identity to a S3 bucket when using the Console as it uses the us-east-1 region for S3 api calls. (Note that it is possible to configure this successfully using IaaC).

fix: update SCP to fix issues with CloudFront using the Console

---

reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json
src/deployments/cdk/src/common/iam-assets.ts
src/lib/custom-resources/cdk-s3-update-logarchive-bucket-policy/runtime/src/index.ts

Allow s3:ListBucket for log archive read-only role. Fixes #798 

Allow s3:ListBucket for log archive read only role

---

src/lib/common/src/scp/index.ts

Currently if the user specifies an SCP that doesn't exist in *global-options/scps* the accelerator warns but doesn't error. It is an easy mistake for users to make when working with the config files, e.g. a typo. Since these are preventative security controls I believe we should fail as the users could incorrectly assume they are protected after running the deployment.

Throw error if SCP doesn't exist

---

src/core/runtime/src/configuration/load-organizations-config.ts

Currently the config validation checks the number of non-accelerator managed SCP's attached to an OU + the SCPs defined on the OU in the config. If this is greater than 5 then the validation fails. This can cause issues if you wish to change the SCP's on an OU to different accelerator managed policies. This results in the policies needing to be manually detached.
This change  updates the config validation to check if the SCP already attached to an OU is an accelerator managed SCP, i.e. exists in "global-config/scps". If it does it does not count it as one of the 5 SCPs, as it will be removed by the accelerator when the SCPs are updated.

Allow accelerator to manage scps defined in global-options section

---

docs/installation/installation.md
reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json

The AMI specified in the sample configuration does not use the right instance-size for Fortinet firewall manager. I updated it along with the version that the AMI uses (6.4.7). 

Changed the Fortinet Manager instance-sizes and updated the version number in the docs

---

pnpm-lock.yaml
src/deployments/cdk/src/deployments/firewall/manager/step-1.ts
src/lib/cdk-constructs/package.json
src/lib/cdk-constructs/src/firewall/instance.ts
src/lib/cdk-constructs/src/firewall/manager.ts
src/lib/custom-resources/cdk-ec2-disable-api-termination/README.md
src/lib/custom-resources/cdk-ec2-disable-api-termination/cdk/index.ts
src/lib/custom-resources/cdk-ec2-disable-api-termination/package.json
src/lib/custom-resources/cdk-ec2-disable-api-termination/tsconfig.json

Set the option disable-api-termination on EC2 instances created for firewall and firewall manager using a custom construct.

(feature) Added termination-protection for Firewalls and Firewall Manager

---

src/deployments/cdk/src/common/ad-users-groups.ts
src/deployments/cdk/src/deployments/rsyslog/step-2.ts
src/lib/cdk-constructs/src/autoscaling/launch-configuration.ts
src/lib/cdk-constructs/src/vpc/asg.ts
src/lib/config-i18n/src/en.ts
src/lib/config-i18n/src/fr.ts
src/lib/config/src/config.v2.ts

Added new configurations (rdgw-enforce-imdsv2 and rsyslog-enforce-imdsv2) that will force IMDSv2 on the launch configurations. If unspecified, the default value for these configuration is false.

(feat) Added possibility to enforce IMDSv2 on launch configuration for RDGW, rsyslog

---

docs/installation/installation.md
reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-CTNFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-GWLB-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json

rename GCWide subnet to App2 subnet for new installs in examples (other doc updates)

rename GCWide subnet to App2 subnet for new installs in examples (other doc updates)

---

docs/installation/sm_inputs.md

Using "targetOUs" (with capital U) will cause the state machine to fail as `targetOus` will be an empty string array.
Example State machine execution input:
Execution fails:
```json
{"scope":"OU","targetOUs":["Prod","Dev"],"mode":"APPLY"}
```
Execution Succeeds:
```json
{"scope":"OU","targetOus":["Prod","Dev"],"mode":"APPLY"}
```
This results in the following if statement in `src/lib/common-config/src/compare/main.ts` evaluating to false and throwing an error:
```typescript
if (ous && ous.length > 0) {
// Changes allowed only in Account configuration for both mandatory and workload
if (ous.includes('ALL')) {
return;
}
const namedOuValidation = configChanges.filter(
cc => cc.path?.[0] !== 'organizational-units' && !ous.includes(cc.path?.[1]),
);
if (namedOuValidation.length > 0) { …
```

(docs)update "targetOUs" to "targetOus" in sm_inputs.md

---

src/lib/common-config/src/compare/main.ts

As far as I can tell `loadOus` is supposed to be `targetOus` in this error message.

Fix error message when scope="OU"

---

src/deployments/cdk/src/deployments/central-services/central-logging-s3/step-1.ts

The State Machine (SM) fails to complete *Deploy Phase 1* when the following configuration is applied:
```
"additional-cwl-regions": {
"us-east-1": {
"kinesis-stream-shard-count": 1
}
},
```
It errors with: **"KinesisStreamRoleLookupPolicyB898FB3A already exists on the role PBMMAccel-Kinesis-Stream-Role-C25E0F50**
This pull request (PR) fixes that issue.

fix for cwl additional region permission bug

---

reference-artifacts/Custom-Scripts/SEA-uninstall/README.md
reference-artifacts/Custom-Scripts/SEA-uninstall/aws-sea-cleanup.py

Added replacement option for HOME_REGION
Allowed to be run against CT baseline. Tested against CT ultralite config
Removed dependency on "deployments" config section as this is not mandatory

Feat: Uninstall script - basic HOME_REGION, CT support, fixed issue with non-mandatory deployment config

---

reference-artifacts/Custom-Scripts/Update-Scripts/v1.3.8_to_v1.5.0/README.md
reference-artifacts/Custom-Scripts/Update-Scripts/v1.3.8_to_v1.5.0/update.py

Some implementations do no use the core OU default name ('core'). The new flag enables support for such cases. Without the flag the Infrastructure OU is not properly populated and the core OU is not renamed to Security.

Added new optional parameter --CoreOU to specify the core OU name.

---

src/deployments/cdk/src/common/nfw.ts
src/deployments/cdk/src/common/vpc.ts

Used a custom construct that succeeds when the log group already exists instead of the default construct.

Fix/issue with CFN stack if the log group already exists for NFW (caused by phase rollback/retry)

---

src/lib/custom-resources/cdk-s3-update-logarchive-bucket-policy/cdk/index.ts
src/lib/custom-resources/cdk-s3-update-logarchive-bucket-policy/runtime/src/index.ts

In some scenarios it is possible that the SM runs that affects the Log Archive S3 Resource Policies without triggering the execution of the **cdk-s3-update-logarchive-bucket-policy** lambda function. This could happen if CloudFormation does not detect/update the lambda function. The result is the custom resource policies are not reapplied. 
This Pull Request 'forces' the update of the **cdk-s3-update-logarchive-bucket-policy** lambda function; thus forcing it to fire each SM run.
To validate the fix:
1. Run the SM and log into the Log Archive Account
2. Locate the lambda function example **ASEA-LogArchive-Phase2-CustomS3UpdateLogArchivePol-jTScdLLzl …

fix for Log Archive Bucket Resource Policies being overwritten 

---

reference-artifacts/Add-ons/opensiem/package-lock.json
reference-artifacts/Add-ons/opensiem/package.json

This updates cdk from 2.10.0 to 2.13.0 and resolves npm audit findings

update opensearch aws-cdk to latest

---

src/lib/common/src/util/common.ts

This PR ensures that the global region is enabled to make sure an instance of ASEA will not break. The code checks to see if us-east-1 is a enabled as a supported region, and if it is not, it adds it to configuration.  Fixes #916

Added function to enable global region

---

src/deployments/cdk/src/apps/phase-1.ts
src/deployments/cdk/src/deployments/defaults/shared.ts
src/deployments/cdk/src/deployments/defaults/step-1.ts
src/deployments/cdk/src/deployments/defaults/step-2.ts

fms custom resource would fail on phase 4 because the ASEA pipeline role did not have the correct permissions for KMS. This fix gives the pipeline role correct permissions to the key.

fix perms where fms would fail to publish to sns

---

src/deployments/cdk/src/deployments/rsyslog/step-2.ts
src/lib/cdk-constructs/src/vpc/asg.ts
src/lib/config-i18n/src/en.ts
src/lib/config-i18n/src/fr.ts
src/lib/config/src/config.v2.ts

This update adds `user-data` to the `rsyslog` deployment type. The issue in #893 can be remediated by changing the user data script.
The following token was added to allow a string replace in the user-data string value. `${SEA:CUSTOM::RsyslogLogGroupName}`

Fix/issue 893 - Add optional user-data to Rsyslog config

---

src/deployments/cdk/src/deployments/iam/step-1.ts
src/lib/common/src/util/common.ts

This resolves the error when loading a yaml config file.
This also resolves the error "Error: Cannot find central log bucket for log account log-archive"
fixes #945

fix yaml load and log bucket output error

---

src/deployments/cdk/src/deployments/iam/sns-subscriber-lambda-role.ts

The root account **ASEA-Management-Phase2-SnsSubscriberLambda** function fails to publish messages to the central account SNS KMS encrypted topics. This pull request updates the Lambda's role permissions to allow the use of KMS.
This issue can be identified by the lack of notifications and viewing the following error in the CloudWatch Logs for the lambda:
```
{
"errorType": "KMSAccessDenied",
"errorMessage": "null (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: 318a7abf-00c8-4b1d-8877-cb1fba8271e5; Proxy: null)",
"code": "KMSAccessDenied",
"message": "null (Service: AWSKMS; Status Code: 400; Error Code: …
```

fix: update SnsSubscriber lambda role permissions to support KMS SNS Topics

---

src/deployments/cdk/src/common/iam-assets.ts

When creating a new IAM policy, any IAM condition blocks in the policy are dropped by the accelerator. Fixes #980 

allow adding iam conditions when creating an iam policy

---

reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-CTNFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-GWLB-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json

- Fix SCP spelling error
- revert rsyslog to IMDSv1 as boot script has v1 dependencies

asea config file tweaks

---

src/mkdocs/docs/installation/install.md
src/mkdocs/docs/installation/upgrades.md

(doc)tweaks-for-153

---

src/deployments/runtime/src/alb-to-alb-target/alb-target-record-monitor.ts

This fixes an issue with the ALB Forwarder when no *hosts* value is specified. From the docs, " `paths` and `hosts` are both optional". The lambda processor function fails with a .length on an undefined object. This pull requests adds a simple check to that condition statement.

fix for issue with ALB forwarder when no HOSTS defined

---

src/core/cdk/src/tasks/store-outputs-task.ts
src/core/cdk/src/tasks/store-outputs-to-ssm-task.ts

Extension of PR:  #1047
Decreasing maxconcurrency  for StoreOutputTasks and StoreOutputsToSSMTasks based on newer default Lambda limits.
This reduces the concurrency of the Store Outputs Phase which invokes additional step functions and Lambdas. This will fix customers with > 40 AWS Accounts seeing the following error:
{
"error": "Lambda.TooManyRequestsException",
"cause": "Rate Exceeded. (Service: Lambda, Status Code: 429, Request ID: ...)"
}

(fix) Decrease max concurrency limit to 10

---

reference-artifacts/Add-ons/opensiem/README.md
reference-artifacts/Add-ons/opensiem/SiemConfig.json
reference-artifacts/Add-ons/opensiem/lib/open-search.ts
reference-artifacts/Add-ons/opensiem/lib/opensearch-siem-stack.ts
reference-artifacts/Add-ons/opensiem/lib/siem-alerts.ts
reference-artifacts/Add-ons/opensiem/lib/siem-cognito.ts
reference-artifacts/Add-ons/opensiem/lib/siem-config.ts
reference-artifacts/Add-ons/opensiem/package-lock.json
reference-artifacts/Add-ons/opensiem/package.json

- Updated the CDK version to v2.40.0
- Updated the OpenSearch cluster with the latest version 1.3 (will cause a Blue/Green Deployment)
- Updated the OpenSearch cluster to use GP3 for the EBS volume type (will cause a Blue/Green Deployment)
- Added 14 CloudWatch Alarms to monitor the OpenSearch cluster based on the recommendations [here](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html)
- Reduced the Lambda Processor memory to 512MB and changed timeout to 2 minutes
- Added a SNS queue to send alerts to registered emails. 
- New configurations:
- "alertNotificationEmails": ["user@email.com"]  CloudWatch …

(addon): OpenSearch SIEM added CW Alarms

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-CTNFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-GWLB-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-CT-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
src/deployments/cdk/src/deployments/guardduty/guardduty.ts
src/lib/config-i18n/src/en.ts
src/lib/config-i18n/src/fr.ts
src/lib/config/src/config.v2.ts
src/lib/custom-resources/cdk-guardduty-admin-setup/cdk/index.ts
src/lib/custom-resources/cdk-guardduty-admin-setup/runtime/src/index.ts

This pull requests implements a new configuration value `"guardduty-frequency"` with the following possible values: `FIFTEEN_MINUTES, ONE_HOUR, SIX_HOURS`
By default, the Frequency for updated findings for GuardDuty is set at the default, SIX_HOURS. 
Here's an example of the result with the following config:
```
"guardduty-frequency": "ONE_HOUR",
```

(enhancement): Frequency for updated findings for GuardDuty

---

reference-artifacts/Add-ons/opensiem/lambdas/common/src/backoff.ts
src/lib/common/src/aws/backoff.ts
src/lib/custom-resources/cdk-cfn-utils/cdk/index.ts

When delayFirstAttempt is set to true, a random wait is added for all calls. This has increased State Machine processing time and 'Add Tags to Shared Resources' may now timeout. This PR switches the *delayFirstAttemp* to false.
Below are the AddTagsToSharedResource processing times:
v1.5.3:
v1.5.4:
This PR:

(enhancement): Adjust the Throttle Backoff setting delayFirstAttempt to false

---

src/deployments/cdk/src/deployments/iam/log-group-role.ts

This role is used by the custom resource to create log groups. Something seems to have changed in the CDK log implementation or in the CW logs creation which is now requiring this IAM action to be in the policy. 
See #1079 for more information.

Add logs:TagLogGroup permission to the log group role 

---

src/deployments/runtime/src/alb-to-alb-target/alb-ip-monitor.ts

Proper error handling for when a DNS entry doesn't resolve; it will no longer crash out, but continue processing other records.
Note the console.log of the failed DNS entry, but how it continues to process.

(fix): update alb ip monitor dns lookup check

---

reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-CTNFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-GWLB-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json

Fix the issue of the AWS Config rule IAM Password Policy as described in Issue #1099 by updating the boolean "TRUE" values to lowercase "true" in each of the applicable SAMPLE_CONFIGS files. 
For existing environments the changes can be applied to the current config and run the state machine with the execution input of {"scope":"GLOBAL-OPTIONS","mode":"APPLY"}.

Fix/issue 1099 - AWS Config rule IAM Password Policy boolean values

---

reference-artifacts/SCPs/ASEA-Guardrails-Part0-CoreOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Part0-WkldOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Part1.json
src/deployments/runtime/src/ou-validation-events/policy-changes.ts

This PR carries two fixes
1. Issue# 1060 - ASEA removes any backup policies attached to the OUs
2. The SCPs to protect ASEA resources based of a ResourceTag condition does not protect from the tag itself being removed
Resolves https://github.com/aws-samples/aws-secure-environment-accelerator/issues/1060

Fix for Issue# 1060: Cannot enforce an AWS Backup Policy

---

src/deployments/cdk/src/deployments/vpc/step-2.ts

This changes the parameters used when calling `new ec2.CfnFlowLog`. 
IMPORTANT: Every S3 VPC Flow Log configuration must first be deleted. It will be recreated after the State Machine executes. The fastest way is to use the ASEA-PipelineRole to the Shared Networking and Perimeter accounts (and Management ForSSO VPC), and to manually remove the S3 VPC Flow Log settings from every VPC.
To reproduce the issue, add the following VPC snippet to a Workload Account in the config.json
```
"vpc": [
{
"deploy": "local",
"name": "Sandbox",
"description": "This VPC is deployed locally in each Sandbox account and each account/VPC is deployed with the same …
```

fix for #1111

---

src/deployments/cdk/src/deployments/defaults/shared.ts
src/deployments/cdk/src/deployments/sns/step-1.ts

EventBridge needs KMS key policy permissions to the Rule Target's SNS KMS CMK. Additionally, the SNS resource policy must allow EventBridge to publish messages. This pull request fixes both issues allowing the SNS Topics to receive alert messages.

fix for EventBridge notifications sent to SNS

---

reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json

closes #1144 
Warning banner in the Billing Console will still exist until 7-JUL, or the new permissions are enabled from the 'Affected Policies' page [here](https://us-east-1.console.aws.amazon.com/poliden/home?region=us-east-1#/)
SCP size is calculated as the following: (<5120)
ASEA-Guardrails-Part0-CoreOUs.json     4963
ASEA-Guardrails-Part0-WkldOUs.json     4057
ASEA-Guardrails-Part1.json     4817
ASEA-Guardrails-Sandbox.json     3253
ASEA-Guardrails-Sensitive.json     4976
ASEA-Guardrails-Unclass.json     4646
Note that this also add sustainability to fix the Carbon Footprint dashboard.

fix: scp updates for the deprecation of aws-portal and purchase-order namespaces

---

reference-artifacts/SAMPLE_CONFIGS/config.SSM-Patching-example.json
reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-CTNFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-GWLB-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-CT-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json

AWS Security Hub retired controls Lambda.4 and PCI.EC2.3. Removing them from the sample configs. See https://docs.aws.amazon.com/securityhub/latest/userguide/doc-history.html

Removing retired security hub controls

---

src/deployments/cdk/toolkit.ts

The updateTerminationProtection function is getting a wrong argument "stack.id" which resulting the termination protection for stack not lifted and deletion of stack fail.

Fix wrong argument passed to the updateTerminationProtection function

---

src/lib/common-types/src/types.ts

Add `ca-west-1` to the list of known regions to pass config validation phases.

add ca-west-1 to list of known regions

---

src/deployments/cdk/src/deployments/guardduty/guardduty.ts

When configuring ca-west-1 the export configuration fails because service principal does not have permissions to write to the central log archive bucket and KMS Key. This Pull Request adds additional logic to support opt-in region service principals.

enables opt-in region for guardduty logging

---

src/lib/cdk-constructs/src/firewall/instance.ts
src/lib/custom-resources/cdk-s3-template/cdk/index.ts
src/lib/custom-resources/cdk-s3-template/runtime/src/index.ts

This fixes the S3 API cross-region call when trying to provision 3rd party firewalls that use a configuration file. If the 3rd party firewalls are being deployed in ca-west-1, but the configuration files are in ca-central-1 (home region) this error will be encountered: `Error: Unable to get S3 object s3://asea-management-phase0-configcacentral1-1g9ucir5s5ry0/firewall/firewall-example-A-A-multitunnel.txt: IllegalLocationConstraintException: The ca-central-1 location constraint is incompatible for the region specific endpoint this request was sent to.`
The fix below uses the config bucket's home region as a parameter to the locationconstraint in the …

fix for cross region s3 template processing

---

src/lib/cdk-constructs/src/vpc/asg.ts

This changes the AutoScalingGroup configuration to use the LaunchTemplate's latest version instead of the hardcoded "1". 
To test:
1. In the config file, change the  `"rsyslog-root-volume-size": 100` value to `150`.
2. Run the StateMachine
You should see the ASG referenced version to be the latest.

fix for 1205

---

src/lib/custom-resources/cdk-transit-gateway-accept-peering/cdk/index.ts
src/lib/custom-resources/cdk-transit-gateway-create-peering/cdk/index.ts

This changes fixes the CDK errors when trying to peer more than 1 TGW.
Original Error
```
rror: There is already a Construct with name 'Custom::TGWCreatePeeringAttachmentRole' in AccountStack [SharedNetworkPhase1CaWest_1]
at Node.addChild (/app/node_modules/.pnpm/constructs@10.2.70/node_modules/constructs/src/construct.ts:428:13)
at new Node (/app/node_modules/.pnpm/constructs@10.2.70/node_modules/constructs/src/construct.ts:71:17)
at new Construct (/app/node_modules/.pnpm/constructs@10.2.70/node_modules/constructs/src/construct.ts:480:17)
at new Resource (/app/node_modules/.pnpm/aws-cdk-lib@2.101.0_constructs@10.2.70/node_modules/aws-cdk-lib/core/l …
```

fix for tgw peering multiple attachments issue

---

src/core/cdk/src/initial-setup.ts
src/core/cdk/src/tasks/enable-optin-region-task.ts
src/core/cdk/src/tasks/run-across-accounts-task.ts
src/core/runtime/src/enable-optin-regions/enable.ts
src/core/runtime/src/enable-optin-regions/index.ts
src/core/runtime/src/enable-optin-regions/verify.ts
src/core/runtime/src/index.ts
src/lib/common/src/aws/account.ts
src/lib/common/src/aws/ec2.ts

This PR introduces a new step in the State Machine that executes a new State Machine that enables opt-in regions, and waits until the enabling is complete. The new SM is configured to run 15 accounts concurrently.
Main State Machine:
New OptIn State Machine:
This improves the experience when creating new AWS accounts by having the SM enable the region instead of using an external script.

Opt-in region State Machine enhancements

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/convert-config.ts

fix(convert-config): Remove warning for ssm-remediation with nested ous in convert-config

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/resource-mapping.ts

fix(resource-mapping) fix nested stacks lookup for resource mapping

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/snapshot/lib/aws-cloudwatch.ts

Skip over subscription filters for log groups with infrequent access storage when running the snapshot tool.

fix(snapshot) skip subscription filters for IA log groups

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/common/aws/config-service.ts
reference-artifacts/Custom-Scripts/lza-upgrade/src/post-migration.ts

Remove config aggregator in post migration while removing config rules.

fix(post-migration) remove asea config aggregator

---

src/lib/custom-resources/cdk-guardduty-create-publish/package.json

Reverts aws-samples/aws-secure-environment-accelerator#1267

Revert "Bump aws-cdk-lib from 2.101.0 to 2.187.0 in /src/lib/custom-resources/cdk-guardduty-create-publish"

---

src/lib/custom-resources/cdk-logs-resource-policy/package.json

Reverts aws-samples/aws-secure-environment-accelerator#1268

Revert "Bump aws-cdk-lib from 2.101.0 to 2.187.0 in /src/lib/custom-resources/cdk-logs-resource-policy"

---

src/lib/custom-resources/cdk-r53-dns-endpoint-ips/package.json

Reverts aws-samples/aws-secure-environment-accelerator#1270

Revert "Bump aws-cdk-lib from 2.101.0 to 2.187.0 in /src/lib/custom-resources/cdk-r53-dns-endpoint-ips"

---

src/core/runtime/package.json

Reverts aws-samples/aws-secure-environment-accelerator#1246

Revert "Bump esbuild from 0.19.4 to 0.25.0 in /src/core/runtime"

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/snapshot.ts
reference-artifacts/Custom-Scripts/lza-upgrade/src/snapshot/snapshotConfiguration.ts

Fetch the list of accounts for snapshot from ASEA Dynamo DB Table instead of AWS Organizations. This ensure snapshot is not run on accounts ignored by ASEA where ASEA cannot assume credentials.

Run snapshot only in ASEA managed accounts

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/convert-config.ts

Because multiRegionTrail is set to true, LZA expects that globalServiceEvents should also be true, otherwise it generates this error during validation:
```
The organization CloudTrail setting multiRegionTrail is enabled, the globalServiceEvents must be enabled as well
```
This PR fixes this by setting `globalServiceEvents` to true in convert-config.

fix(convert-config): set globalServiceEvents to true for multiRegionTrail

---

src/deployments/cdk/src/deployments/iam/log-group-role.ts
src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts

This PR adds the KMS Encrypt, Decrypt, and GenerateDataKey to the CustomResource IAM Role.
This resolves the new error: `assumed-role/ASEA-Perimeter-Phase-1-CustomLogsLogGroup49AC86AD-NKwAHgWk8y9J/ASEA-Perimeter-Phase1-CustomLogsLogGroupLambda2441-PUpuy08ZjI1K is not authorized to perform: kms:Encrypt on resource`

fixes issue with CloudWatch Logs custom log KMS permissions

---

reference-artifacts/ssm-documents/attach-iam-role-policy.yaml
reference-artifacts/ssm-documents/ssm-patching-role-tagging.yaml

Update the python version to 3.11 in the SSM Documents ahead of the 10-SEPT deprecation date.

fix: bump python version to 3.11 for SSM Documents

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/convert-config.ts
src/mkdocs/docs/lza-upgrade/comparison/kms.md

Updated convert-config to disable creation of CMK for SQS in LZA config. Starting with LZA v1.12.0 CMK are created for every account and region where LZA is enabled.

fix(convert-config): disable CMK for SQS

---

src/mkdocs/docs/lza-upgrade/asea-resource-handlers.md
src/mkdocs/docs/lza-upgrade/asea-resource-removal.md

chore: add documentation on removal of ASEA resources

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/convert-config.ts
src/mkdocs/docs/lza-upgrade/known-issues.md

Fix the VPC Endpoint default policy in convert-config.
Add documentation to known issues.

fix: convert-config vpc endpoint default policy

---

src/mkdocs/docs/lza-upgrade/upgrade/preparation-steps.md

Adding Amazon Macie account status check
