docs/developer/developer-guide.md

Update language around CDK

---

CONTRIBUTING.md
docs/developer/developer-guide.md

Fixed spelling error - Principal vs Principle

---

docs/architectures/pbmm/architecture.md

Documentation update logging SSM Session Manager

---

README.md

Updated relationship to Control Tower

---

docs/installation/installation.md

- Document procedures for adding subnets to existing VPC
- Document process for updating endpoints

Document config file change processes

---

reference-artifacts/SCPs/PBMMAccel-Guardrails-Part2.json

- neptune does not support condition keys

(fix): SCP tweak - fix neptune issue

---

docs/installation/installation.md

Add clarity to install guide 2.5.22.2

---

README.md
docs/installation/installation.md

fix filepath, andd note on issue

---

src/core/runtime/src/ou-validation.ts
src/deployments/runtime/src/ou-validation-events/move-account-organization.ts
src/deployments/runtime/src/ou-validation-events/remove-account-from-organization.ts
src/lib/cdk-accelerator/src/stepfunction-tasks/code-task.ts
src/lib/common/package.json
src/lib/common/src/util/common.ts
src/lib/common/src/util/prettier.ts

fix(core): Ou-Validation Timeout

---

src/deployments/cdk/src/deployments/config/create.ts

fix(core): Quick fix for deploying remediation action in SSM Deployed account

---

docs/installation/installation.md
reference-artifacts/config.example.json
reference-artifacts/config.lite-example.json

(docs) tweak for new release

---

README.md

tweak overview

---

src/deployments/cdk/src/deployments/defaults/outputs.ts
src/deployments/runtime/src/ou-validation-events/move-account-organization.ts

fix(core): Fixing upgrade issue

---

docs/installation/installation.md

(doc)add v1.1.4 to v1.2.3 upgrade instructions

---

src/deployments/cdk/src/deployments/ou-validation-events/create-organization.ts
src/deployments/cdk/src/deployments/ou-validation-events/policy-changes.ts
src/deployments/cdk/src/deployments/ou-validation-events/remove-account.ts
src/deployments/cdk/src/deployments/ou-validation-events/step-1.ts
src/deployments/runtime/src/ou-validation-events/move-account-organization.ts
src/deployments/runtime/src/ou-validation-events/remove-account-from-organization.ts
src/lib/common/src/aws/dynamodb.ts
src/lib/common/src/util/common.ts

- Incresing memorySize for Deployment time Lambda functions also
- Replace Secrets Manager with DynamoDB for accounts in RemoveAccountFromOrganization event

fix(core): Fixing Remove Account with respect to moving Account to DynamoDB

---

src/lib/common/src/util/common.ts

fix(core): Fixing multiple config files with array in separate file

---

docs/installation/installation.md
reference-artifacts/Custom-Scripts/SEA-uninstall/README.md
reference-artifacts/config-sample-snippets/sample_snippets.md
reference-artifacts/config.ALZ.json
reference-artifacts/config.example.json
reference-artifacts/config.lite-example.json

- config files
- installation doc
- uninstall script
- sample snippets

(docs) Fix Typos and make minor enhancements

---

docs/installation/installation.md

- minor improveprovements/clarifications
- document Ultralite config issues

(doc)install doc improvements

---

README.md
docs/developer/developer-guide.md
docs/index.md

(docs) Finalize developer guide

---

src/deployments/cdk/src/apps/phase-1.ts

fix(core): Fix issue with ultra lite configuration and IAM policy definitions

---

src/deployments/cdk/src/apps/phase-2.ts
src/lib/custom-resources/cdk-security-hub-disable-controls/runtime/src/index.ts
src/lib/custom-resources/cdk-security-hub-enable/runtime/src/index.ts

- Updating Security Hub Standards and Controls based on Configuration file

fix(core): Updating Security Hub Standards based on Configuration file

---

reference-artifacts/config.example.json
reference-artifacts/config.lite-example.json
src/deployments/cdk/src/apps/phase-0.ts
src/deployments/cdk/src/apps/phase-1.ts
src/deployments/cdk/src/deployments/central-endpoints/dns-query-log-group.ts
src/deployments/cdk/src/deployments/central-endpoints/index.ts
src/deployments/cdk/src/deployments/central-endpoints/step-1.ts
src/deployments/cdk/src/deployments/central-endpoints/step-2.ts
src/deployments/cdk/src/deployments/central-endpoints/step-3.ts
src/deployments/cdk/src/deployments/central-endpoints/step-4.ts
src/deployments/cdk/src/deployments/central-endpoints/step-5.ts
src/deployments/cdk/src/deployments/cleanup/step-2.ts
src/lib/common-config/src/index.ts

fix(core): Moving zones configuration to Vpc Config

---

src/core/cdk/src/initial-setup.ts
src/lib/cdk-accelerator/src/stepfunction-tasks/code-task.ts

- Creating Alias "live" and assiging latest version to it
- Replacing SM deprecations with appropriate methods of CDK

fix(upgrade): Using Lambda Alias for Deployment in SM

---

reference-artifacts/config.example.json
reference-artifacts/config.lite-example.json

- add 93 config rules
- remove ALZ references in SCP names
- enable S3 bucket rule auto-remediation

Sample Configuration file updates

---

reference-artifacts/SCPs/PBMMAccel-Guardrails-Part1.json
reference-artifacts/SCPs/PBMMAccel-Guardrails-Part2.json

-(config)Tweak SCP account suspension

(config)Tweak SCP account suspension

---

README.md
docs/developer/release-process.md
docs/faq/faq.md
docs/index.md
docs/installation/customization-index.md
docs/installation/installation.md
docs/operations/operations-troubleshooting-guide.md
reference-artifacts/config.ALZ.json
reference-artifacts/config.example.json
reference-artifacts/config.lite-example.json

- match MAD and IAM password policies in config files
- remove FWMgr from Full sample PBMM config file
- move Accelerator release process to separate file
- move config file customization information to config file customization page/file
- move FAQ to separate file
- enhance install doc
- add details to root password recovery
- add MFA details
- minor enhancements readme, index
- add 4 more answers to Q&A/Operations Info
- remove no longer relevant upgrade information for old versions
- add Joel's FAQ's/update Ops guide with answer 5.
- By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

(docs) Enhance multiple documents (FAQ, Installation, readme, Ops, index)

---

reference-artifacts/config.example.json
src/lib/cdk-constructs/package.json

pin 3rd party dependency version and revert a config file change

---

.github/workflows/documentation.yml
README.md
docs/index.md
docs/installation/customization-index.md
docs/installation/installation.md
reference-artifacts/CONFIG_SAMPLES_MOVED.md
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
reference-artifacts/SAMPLE_CONFIGS/readme.md

- add an ultra-light sample configuration file
- add a multi-region sample configuration file
- tweak Install document to better reflect multiple config file options
- move sample config files into a sub-folder and update all links
- update config file customization guide with new samples and pointer to the samples folder
- additional minor tweaks to install document
- update config files removing alz version parameter and updating sample email addresses

(docs)Add additional sample config files and update docs to reflect

---

src/core/cdk/src/initial-setup.ts
src/core/runtime/src/get-or-create-config.ts
src/lib/common/src/aws/stepfunctions.ts

- Stop duplicate SM execution by validating in getOrCreateConfig step.

fix(core): Stop Duplicate Accelerator execution

---

src/deployments/cdk/src/deployments/ou-validation-events/create-account.ts
src/deployments/runtime/src/ou-validation-events/create-account/add-quarantine-scp.ts
src/deployments/runtime/src/ou-validation-events/create-account/index.ts
src/deployments/runtime/src/ou-validation-events/create-account/invocation-check.ts
src/deployments/runtime/src/ou-validation-events/create-organization.ts
src/deployments/runtime/src/ou-validation-events/move-account-organization.ts
src/deployments/runtime/src/ou-validation-events/policy-changes.ts
src/deployments/runtime/src/ou-validation-events/remove-account-from-organization.ts
src/deployments/runtime/src/ou-validation-events/utils.ts

- Adding additional Lambda step in CreateAccount Trigger SM to validate invocation

fix(core): CreateAccount trigger failure

---

.github/ISSUE_TEMPLATE/bug-report---deployed-functionality.md
.github/ISSUE_TEMPLATE/bug-report---documentation.md
.github/ISSUE_TEMPLATE/bug-report---other.md
.github/ISSUE_TEMPLATE/bug-report---state-machine-failure.md
.github/ISSUE_TEMPLATE/feature_request.md
docs/architectures/pbmm/architecture.md
docs/faq/faq.md
docs/installation/customization-index.md
docs/installation/installation.md
docs/installation/what-we-do-where.md
docs/operations/operations-troubleshooting-guide.md

(docs)Updates in preparation for v1.2.5

---

src/deployments/runtime/src/ou-validation-events/policy-changes.ts

- Ignore PolicyChange event if it is performed on Ignored Ou or Accounts under IgnoredOu

fix(core): PolicyChanges by adding ignoredOu validation

---

src/lib/custom-resources/cdk-s3-update-logarchive-bucket-policy/runtime/src/index.ts

Fix incorrect parameter in Log Archive Read Only custom resource

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/sample_snippets.md
reference-artifacts/config.ALZ.json
reference-artifacts/config.example.json

update-parameter-name in sample configs

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
reference-artifacts/SCPs/PBMMAccel-Guardrails-Part2.json

- add KMS SCP protection
- add IAM IP CW Event
- fix CW Event IP ranges and MFA example

CW and SCP tweaks

---

.github/workflows/documentation.yml

- add additional samples
- try fixing wide tables

fix doc generation

---

CONTRIBUTING.md
docs/installation/installation.md

-also add link to code of conduct to remove github nag

(docs)improve upgrade instructions

---

docs/faq/faq.md
docs/installation/multi-file-config-capabilities.md

(docs)clarify cert FAQ and tweak multi-part config file docs

---

src/deployments/cdk/src/apps/phase-1.ts
src/deployments/cdk/src/common/iam-assets.ts

- Reading Organizational-Units config for policy definitions

fix(core): IAM Policy creation based on Org config

---

src/core/runtime/src/ou-validation.ts
src/lib/common/src/util/common.ts

fix(core): Fixing remove account or Leave from organization action trigger

---

docs/installation/installation.md
src/deployments/cdk/src/deployments/defaults/shared.ts
src/deployments/cdk/src/deployments/defaults/step-1.ts
src/deployments/cdk/src/deployments/ssm/session-manager.ts
src/lib/cdk-accelerator/src/core/secrets-container.ts

feat(core): Adding Automatic rotation to KMS Key

---

docs/installation/installation.md
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
reference-artifacts/SCPs/ASEA-Guardrails-Part0.json
reference-artifacts/SCPs/ASEA-Guardrails-Part1.json
reference-artifacts/SCPs/ASEA-Guardrails-Part2.json
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json

Clarify v1.2.4 upgrade requirements, prettier SCP files

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json

(config)Fix config file formatting

---

src/installer/cdk/src/index.ts

- Adding validation to Accelerator Name and Prefix
- Forcing - at the end for Accelerator Prefix

fix(installer): Adding validation to Accelerator Name and Prefix

---

docs/installation/installation.md

(docs)update upgrade details for v1.2.6

---

src/installer/cdk/assets/validate-parameters.js

fix(1.2.6): Catch exception on ssm GetParam for accelerator/version

---

src/core/runtime/src/get-or-create-config.ts
src/installer/cdk/assets/start-execution.js
src/installer/cdk/src/index.ts
src/installer/cdk/test/start-execution.spec.ts

- Adding 4 character limit to AccelName and 10 character limit to AccelPrefix
- Checking for "mode: APPLY" when scope is provided as input to SM if not then fail SM

Adding validation to accelName, Prefix and Mode

---

docs/faq/faq.md

Introducing "chain" attribute to import certificates with chain.

---

.github/workflows/documentation.yml
.github/workflows/publish.yml
.github/workflows/release.yml
docs/developer/developer-guide.md
docs/developer/release-process.md
docs/installation/installation.md
reference-artifacts/Custom-Scripts/Import-Account-CFN-Role-Template.yml
reference-artifacts/Custom-Scripts/SEA-uninstall/README.md
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
reference-artifacts/SAMPLE_CONFIGS/sample_snippets.md

(docs)rename GitHub branch, root account

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json

Adding additional VPC flow logs metadata to four sample configs - related to issue #649

---

src/core/runtime/src/get-or-create-config.ts
src/installer/cdk/src/index.ts
src/lib/common/src/aws/codecommit.ts

fix(core): Changing default branch name of config repo to main

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SCPs/ASEA-Guardrails-Part1.json

Fix sample configs and scp

---

.github/workflows/lint-prettier.yml
.github/workflows/release.yml
.gitignore
docs/developer/developer-guide.md
pnpm-lock.yaml
src/core/cdk/cdk.sh
src/installer/cdk/src/index.ts
src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts

- Pushing pnpm-lock.yaml file and using that while install

fix(core): Fixing install and update issues

---

src/deployments/cdk/src/deployments/defaults/step-1.ts

fi(core):Add missing secureTransport for logArchive bucket

---

reference-artifacts/Custom-Scripts/SEA-uninstall/aws-sea-cleanup.py

edited to support cleanup without directory services enabled

---

reference-artifacts/SCPs/ASEA-Guardrails-Part2.json

(fix) Root User unable to change support plans and change MFA (#686)

---

.github/workflows/build.yml
.github/workflows/lint-prettier.yml
.github/workflows/release.yml
src/installer/cdk/src/index.ts
src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts

- Installing 5.18.9 version of pnpm which is last supported by nodejs:12.6

fix(core): pnpm installation issue

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json

added toggle to enable security hub by default

---

docs/architectures/pbmm/architecture.md
docs/faq/faq.md
docs/installation/customization-index.md
docs/installation/installation.md
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json

(docs) updates for v1.3.2

---

src/core/cdk/src/initial-setup.ts
src/core/runtime/src/load-accounts-step.ts
src/deployments/cdk/src/deployments/config/create.ts
src/deployments/cdk/toolkit.ts
src/installer/cdk/assets/start-execution.js
src/installer/cdk/test/start-execution.spec.ts

Enable `CDK_DEBUG` flag when `"verbose"` state machine input is set to `"1"`.
Also add additional config rule logs and print CloudFormation template.

feature(core): Add additional CDK logging

---

src/deployments/cdk/src/deployments/iam/guardduty-roles.ts
src/lib/custom-resources/cdk-guardduty-admin-setup/runtime/src/index.ts

fix(core): Fix GuardDuty issue related to member account enable

---

docs/installation/installation.md

(docs)clarify v1.3.3 upgrade instructions

---

.github/workflows/lint-prettier.yml
src/deployments/cdk/src/apps/phase-1.ts
src/deployments/cdk/src/common/vpc.ts
src/deployments/cdk/src/deployments/transit-gateway/step-2.ts
src/deployments/cdk/test/common/vpc.spec.ts
src/installer/cdk/src/index.ts
src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts
src/lib/common-outputs/src/transit-gateway.ts

fic(core): Fixing TGW Cross account attachment

---

src/deployments/cdk/src/deployments/transit-gateway/step-3.ts
src/lib/custom-resources/cdk-guardduty-admin-setup/runtime/src/index.ts

- (Breaking) Need to remove blackhole-routes from "deployments/tgw/<idx>/tgw-routes" because of construct name changes.

fix(core): Fix creating TGW Static Routes

---

docs/faq/faq.md
docs/installation/customization-index.md
docs/installation/installation.md
reference-artifacts/CONFIG_SAMPLES_MOVED.md
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
reference-artifacts/SCPs/ASEA-Guardrails-Part1.json
reference-artifacts/SCPs/ASEA-Guardrails-Part2.json
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json

Create test PBMM config, reducing costs, other minor tweaks and doc updates

---

reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json

move off deprecated ami

---

src/deployments/cdk/src/deployments/firewall/cluster/outputs.ts
src/deployments/cdk/src/deployments/firewall/cluster/step-2.ts
src/lib/cdk-constructs/src/firewall/instance.ts

fix(core): Fixing VPN Tunnel options for Static cgw routing

---

docs/faq/faq.md

Added FAQs and minor change to FAQ document

---

src/core/runtime/src/store-stack-output-step.ts
src/deployments/cdk/package.json
src/deployments/cdk/toolkit.ts
src/lib/cdk-accelerator/src/core/accelerator-stack.ts

fix(core): Fix adding stack level tags and handling duplicate Accelerator tag

---

reference-artifacts/SAMPLE_CONFIGS/BAD-config.test-example.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json

Update Fortigate ami's/Mark invalid sample config file

---

docs/installation/installation.md

Tweak docs for release

---

reference-artifacts/SAMPLE_CONFIGS/BAD-config.test-example.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json

Latest config samples tweaks

---

docs/installation/installation.md
docs/installation/object-naming.md
reference-artifacts/Custom-Scripts/SEA-uninstall/README.md
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json
src/lib/cdk-constructs/src/firewall/instance.ts

Various fixes-access-analyzer-FW-Docs

---

src/deployments/cdk/src/deployments/iam/guardduty-roles.ts
src/deployments/cdk/src/deployments/iam/macie-roles.ts
src/lib/custom-resources/cdk-guardduty-enable-admin/runtime/src/index.ts
src/lib/custom-resources/cdk-macie-enable-admin/runtime/src/index.ts

retries implemented for gd and macie.

---

src/deployments/cdk/src/deployments/iam/guardduty-roles.ts
src/deployments/cdk/src/deployments/iam/macie-roles.ts
src/lib/custom-resources/cdk-guardduty-enable-admin/runtime/src/index.ts
src/lib/custom-resources/cdk-macie-enable-admin/runtime/src/index.ts

Authored-by: Dustin Hickey <hickeydh@amazon.amazon.com>

Fix GD and Macie activation issues

---

docs/faq/faq.md
docs/installation/installation.md
reference-artifacts/SAMPLE_CONFIGS/sample_snippets.md

Update docs for v137

---

src/lib/custom-resources/cdk-guardduty-admin-setup/runtime/src/index.ts

Fixed nextToken bug causing infinite loop in the guard duty admin setup custom resource

fixed infinite loop.

---

src/lib/common/src/aws/directory-service.ts

Fixes pagination problem for multiple accounts with directory services sharing.

ds pagination fix

---

reference-artifacts/Custom-Scripts/Developer-Scripts/src/load-outputs.ts
src/deployments/cdk/toolkit.ts
src/lib/custom-resources/cdk-security-hub-accept-invites/runtime/src/index.ts
src/lib/custom-resources/cdk-security-hub-disable-controls/runtime/src/index.ts

Added pagination for codebuild deployments and some auxiliary functions.

added pagination

---

docs/installation/customization-index.md
docs/installation/installation.md
reference-artifacts/Custom-Scripts/Developer-Scripts/README.md
reference-artifacts/Custom-Scripts/Developer-Scripts/package.json
reference-artifacts/Custom-Scripts/Developer-Scripts/tsconfig.json

tweak docs for v1.3.8

---

src/core/runtime/src/create-stack/verify.ts

added verify retries

---

src/core/cdk/src/tasks/cdk-bootstrap.ts
src/core/runtime/src/create-stack/verify.ts

fixed stack verify

---

reference-artifacts/SCPs/ASEA-Guardrails-Part1.json

fix-cdk-s3-scp

---

reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json

fix-ul-config-file

---

src/deployments/cdk/src/common/interface-endpoints.ts

Before the upgrade process, comment out all endpoints with a '.' in its name and run the StateMachine. This will remove the targeted endpoints. Re-enable the '.' endpoints and the SM will recreate them with the applied fix.

fix: ECR Endpoints Not Functional #809

---

src/core/cdk/src/initial-setup.ts
src/deployments/cdk/cdk.ts
src/deployments/cdk/codebuild-deploy.sh
src/deployments/cdk/toolkit.ts
src/installer/cdk/src/index.ts

Fixed debugging to print out only when thresholds are passed
Fixed Pagination memory issue
Fixed Heap size based on CodeBuild instance type. 
Added account and region for logging

fixed pagination and debugging

---

.github/workflows/build.yml
.github/workflows/lint-prettier.yml

Modified the pipeline with the latest strategy.

Update pr mr tests

---

reference-artifacts/SAMPLE_CONFIGS/config.ultralite-CT-example.json

(config)Add CT UltraLite example

---

docs/architectures/pbmm/architecture.md
docs/faq/faq.md
docs/installation/customization-index.md
docs/installation/installation.md
reference-artifacts/Custom-Scripts/SEA-uninstall/README.md
reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-CTNFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-GWLB-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json

(docs)Multiple doc enhancements

---

reference-artifacts/Custom-Scripts/Developer-Script/package.json

Updated aws-sdk version for dev scripts

---

reference-artifacts/Third-Party/firewall-example-A-A-multitunnel.txt

fix/issue 887 - Update firewall-example-A-A-multitunnel.txt to fix outbound asymmetric routing issue

---

README.md

documentation: updated README with new workshop details

---

reference-artifacts/SCPs/ASEA-Guardrails-Part0-CoreOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Part0-WkldOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Part1.json
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json
reference-artifacts/SCPs/Quarantine-New-Object.json

Implements the changes described in the issue.

Fix/issue 871 - aws-controltower-ConfigRecorderRole is blocked by SCP

---

reference-artifacts/SCPs/ASEA-Guardrails-Part1.json
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json

(fix)tweaks-for-control-tower-28-changes

---

reference-artifacts/Add-ons/opensiem/README.md

(docs)Update opensiem install instructions w/extra details

---

src/lib/common/src/util/common.ts

This fixes the bug where the config is written to the raw config and vice versa.

fixed-enable-global-region function

---

pnpm-lock.yaml
src/ui/package.json

updated awsui react comps

---

.github/workflows/release.yml

(docs)fix doc gen process

---

src/lib/common/src/util/common.ts

Throws an explicit error message if one of the mandatory config sections is missing.

fixed missing vpc config section

---

src/core/runtime/src/add-scp-step.ts
src/deployments/runtime/src/ou-validation-events/policy-changes.ts

ignore attach/detach scps to nested OUs

---

docs/installation/installation.md

(d0cs) Update installation docs for v151

---

docs/installation/installation.md

Update installation.md for 151a

---

README.md

Fix broken link in README of main

---

src/mkdocs/docs/installation/index.md
src/mkdocs/mkdocs.yml

(docs)tweak menus

---

reference-artifacts/Add-ons/DDB-Update/ddb-update.yaml

Enabled Versioning on the S3 Bucket

---

src/mkdocs/docs/installation/services-list.md

This PR reformats the table of the service list page.

Update service list page

---

README.md

Point to new documentation site post-installation steps

Update README.md post-installation to new documentation site and post-installation page.

---

README.md
reference-artifacts/Add-ons/opensiem/README.md
src/mkdocs/docs/pricing/sample_pricing.md

(docs)broken-links

---

reference-artifacts/Add-ons/opensiem/README.md
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json

- This fix is required to enable deploying Red Hat OpenShift

(fix)scp tweak - allow reading tags outside home region

---

src/deployments/runtime/src/ou-validation-events/policy-changes.ts

fixed Control Tower SCPs being removed unexpectedly

---

reference-artifacts/SAMPLE_CONFIGS/readme.md
src/lib/config-i18n/src/en.ts

tweak en.ts and broken link

---

src/deployments/cdk/src/common/account-stacks.ts
src/deployments/cdk/src/common/vpc.ts
src/lib/cdk-plugin-assume-role/src/assume-role-provider-source.ts

this fixes the problem when deploying accounts keys that starts with a number. fixes #972

Fix number account name

---

reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-CTNFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-GWLB-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json
reference-artifacts/SAMPLE_CONFIGS/config.test-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-CT-example.json
reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json
src/mkdocs/docs/installation/install.md

(docs) clarify mgmt account naming in the config file

---

README.md
src/mkdocs/docs/index.md
src/mkdocs/docs/installation/install.md

(docs) Tweaks docs for AMI issue and CT latest

---

src/mkdocs/docs/faq/index.md

(docs): Eb faq doc update

---

src/core/cdk/src/assets/execution-role.template.json
src/core/cdk/src/assets/management-execution-role.template.json
src/core/runtime/src/create-stack/create.ts

--
Fixing Source Template to correct arn in conditional principal arn statement.
This fix will address the below issue.
```
Could not assume role in target account using credentials returned by plugin 'cdk-assume-role-plugin' 
```

Fixing template source to correct Condition role arn

---

reference-artifacts/Add-ons/DDB-Update/README.md
reference-artifacts/Add-ons/opensiem/README.md

Put the disclaimer in each example readme.md file for Add-on examples

Add disclaimer to the top of the ReadMe files for all Add-ons

---

src/mkdocs/docs/installation/install.md

(docs)tweaks-for-v155

---

README.md

Update to README.md to include LZA Notice

---

reference-artifacts/SAMPLE_CONFIGS/config.example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.example.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example-oldIP.json
reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json
reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json

update Fortinet amis to FW - 6.4.11, Mgr - 6.4.9

(config)Fortinet ami update

---

reference-artifacts/SCPs/ASEA-Guardrails-Part0-CoreOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Part0-WkldOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Part1.json
src/deployments/runtime/src/ou-validation-events/policy-changes.ts

Reverts aws-samples/aws-secure-environment-accelerator#1106

Revert "Fix for Issue# 1060: Cannot enforce an AWS Backup Policy"

---

pnpm-lock.yaml
src/installer/cdk/package.json

Fix github workflow for cdk synth

updated installer stack cdk

---

src/installer/cdk/src/index.ts

Fixed installer stack naming

---

reference-artifacts/SCPs/ASEA-Guardrails-Part1.json
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json

The following SCP optimizations include:
- Consolidation of common prefixed APIs with a wildcard
- Removal of unused APIs (as reported by `aws accessanalyzer validate-policy`)

SCP Optimizations

---

pnpm-lock.yaml
src/lib/custom-resources/cdk-ec2-vpn-tunnel-options/runtime/package.json

Bump xml js version

---

reference-artifacts/SCPs/ASEA-Guardrails-Part0-CoreOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Part0-WkldOUs.json
reference-artifacts/SCPs/ASEA-Guardrails-Sandbox.json
reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json
reference-artifacts/SCPs/ASEA-Guardrails-Unclass.json

Scppatches

---

src/lib/cdk-accelerator/src/core/secrets-container.ts

fixed policy synth

---

src/deployments/runtime/src/ou-validation-events/policy-changes.ts

Issue# 1060 - ASEA removes any backup policies attached to the OUs
Resolves #1060

Policy changes rule must only revert SCPs; not backup or tag policies

---

src/installer/cdk/src/index.ts
src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts

Codebuildpatch

---

README.md

Updating support timeline in readme.

Updating support timeline in readme

---

src/deployments/cdk/promise.ts

Added stack trace to errors

---

src/deployments/cdk/src/deployments/cloud-watch/step-3.ts

added section to security hub rules

---

src/deployments/cdk/src/apps/phase-2.ts

Fix issue with vpcEndpoint az lookup

---

src/deployments/cdk/src/deployments/metadata-collection/index.ts

Fix Metadata Collection Lambda

---

src/deployments/cdk/src/common/alb-ip-forwarding.ts

Fix for https://github.com/aws-samples/aws-secure-environment-accelerator/issues/1203.

Increase alb ip forwarding lambda memory

---

reference-artifacts/Add-ons/opensiem/lambdas/common/src/backoff.ts
src/lib/common/src/aws/backoff.ts
src/lib/custom-resources/cdk-cfn-utils/cdk/index.ts

update retry logic to match error

---

pnpm-lock.yaml
src/deployments/cdk/package.json

removed proxy-agent dependency

---

src/mkdocs/Makefile
src/mkdocs/mkdocs.yml

removed strict flag

---

pnpm-lock.yaml
src/deployments/cdk/package.json

added latest proxy-agent version

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/resource-mapping.ts

fix(resourcemapping): added compare and next token for list stack

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/convert-config.ts

feat(convert-config): adding lza vpcflowlog log group pattern to dynamic parition

---

reference-artifacts/Custom-Scripts/lza-upgrade/CHANGELOG.md
src/mkdocs/README.md
src/mkdocs/docs/lza-upgrade/faq.md
src/mkdocs/docs/lza-upgrade/known-issues.md
src/mkdocs/docs/lza-upgrade/preparation/prereq-config.md
src/mkdocs/docs/lza-upgrade/troubleshooting.md

Prepare changelog for ASEA v1.6.1
Documentation improvements for LZA upgrades

Lza upgrade doc ASEA v1.6.1

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/convert-config.ts

fix(upgrade): include all dns-resolver-query logs in config

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/snapshot/lib/aws-kms.ts

fix(upgrade) don't fail on errors when snapshot kms keys

---

reference-artifacts/Custom-Scripts/lza-upgrade/src/common/outputs/load-assigned-cidrs.ts
reference-artifacts/Custom-Scripts/lza-upgrade/src/convert-config.ts

fix(convert-config): fix sub-pool missing in assignedCidr filter 

---

src/mkdocs/docs/lza-upgrade/known-issues.md

chore(documentation): Update known issues for ASEAResources.json

---

src/mkdocs/docs/lza-upgrade/comparison/feature-specific-considerations.md
src/mkdocs/docs/lza-upgrade/comparison/index.md
src/mkdocs/docs/lza-upgrade/preparation/prereq-config.md
src/mkdocs/docs/lza-upgrade/upgrade/finalize.md
src/mkdocs/docs/lza-upgrade/upgrade/install-lza.md
src/mkdocs/docs/lza-upgrade/upgrade/optional-steps.md

LZA upgrade documentation updates
- Added info about CloudTrail differences between ASEA and LZA
- Added steps to move ALB Forwarding rules to LZA table
- Recommendations about Sentinel role
- Upgrade tools should be run on Unix based shell (not Windows)

ASEA to LZA documentation updates

---

deployment/cdk-solution-helper/package-lock.json
deployment/cdk-solution-helper/package.json

fix(packages): remove obsolete fs reference
